% Place parameters from specified GP into parameter vector.
function x = vigpirlpackparam(gp)
  x = vertcat(vigpirlhpxform(gp.rbf_var, [], 'exp', 3),...
    vigpirlhpxform(gp.inv_widths, [], 'exp', 3)',...
    vigpirlhpxform(diag(gp.B), [], 'exp', 3), gp.mu, get_lower_triangle(gp.B));
