% Fill in default parameters for the GPIRL algorithm.
function algorithm_params = vigpirldefaultparams(algorithm_params)

% Create default parameters.
default_params = struct(...
    ...% These are initial values.
    'ard_init',1,...
    'noise_init',1e-2,...
    'rbf_init',5,...
    'warp_c_init',2.0,...
    'warp_l_init',1,...
    'warp_s_init',1,...
    ...% These parameters control how the inducing points are selected.
    'inducing_pts','examplesplus',...
    'inducing_pts_count',16,...
    'samples_count',100);

% Set parameters.
algorithm_params = filldefaultparams(algorithm_params,default_params);
